let suggestions = [
   "Shop Online",
   "Real Estate",
   "Air Tickets",
   "Anything on Hire",
   "Loans",
   "Auto care",
   "Automobile",
   "Baby Care",
   "Banquets",
   "Bills & Recharge",
   "Book Hotel",
   "Pest Control",
   "Bus",
   "Cabs & Car rentals",
   "Caterers",
   "Chemists",
   "Civil Contractors",
   "Courier",
   "Daily Needs",
   "Dance & Music",
   "Doctor",
   "Education",
   "Emergency",
   "Event Organizer",
   "Fitness",
   "Flights",
   "Foreign Exchange",
   "Flowers",
   "Home Decor",
   "Home Improvements",
   "Hospitals",
   "House Keeping",
   "Industrial Products",
   "Insurance",
   "Interior Designer",
   "International SIM Card",
   "Internet",
   "Jewellery",
   "Labs",
   "Language Classes",
   "Loan & Credit Card",
   "Medical",
   "Modular Kitchen",
   "On Demand Services",
   "Packers and Movers",
   "Party",
   "Personal Care",
   "Books",
   "Pet and Pet Care",
   "Real Estate",
   "Repairs",
   "Restaurants",
   "Security Services",
   "Sports Coach",
   "Sports Goods",
   "Train",
   "Training Institute",
   "Transporters",
   "Wedding",
];
